# Map path - relative to Starcraft
map = 'maps\BroodWar\SomeMap.scm'

# Game Type
# Only Melee is supported currently, it takes a list of bots that should play and their respective name and race override
# Ie. - this will run NitekatT 2 times, once it will play as protoss, the second instance will play using the bots preferred race (terran)
game_type = { Melee = [{name = "NitekatT", race = "Protoss"}, {name = "NitekatT"}, {name = "MarineHell"}, {name = "ZergHell"}] }

# This one will run NiteKatT and ZergHell in a window, so you can observe
# Known bug: If the game is hosted by a headful bot, it will not be created automatically - you'll have to click 'create'
#game_type = { Melee = [{name = "NitekatT", race = "Protoss", headful = true}, {name = "MarineHell"}, {name = "ZergHell", headful = true}] }

# Want to join the fray? Uncomment this and open a game
# human_host = true

# Only relevant, when not hosting: Uncomment to set the game speed to "fastest" instead of "as fast as possible"
# human_speed = true